config-version: 2
name: 'integration_tests'
version: '0.1.0'

flags:
  send_anonymous_usage_stats: false

profile: 'integration_tests'

quoting:
  database: false
  schema: false
  identifier: false

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"
